minor bugfixes in plotting scripts

diff --git a/scripts/tag-run-all b/scripts/tag-run-all
--- a/scripts/tag-run-all
+++ b/scripts/tag-run-all
@@ -23,17 +23,18 @@ _run() {
     local FORCE=''
     local CLEAN=''
     local opt
-    while getopts "hfc" opt $@; do
+    while getopts ":hfc" opt $@; do
 	case $opt in
 	    h) _help; return 1;;
 	    f) FORCE=1 ;;
 	    c) CLEAN=1 ;;
+	    # handle errors
+	    \?) _usage; echo "Unknown option: -$OPTARG" >&2; exit 1;;
+            :) _usage; echo "Missing argument for -$OPTARG" >&2; exit 1;;
+            *) _usage; echo "Unimplemented option: -$OPTARG" >&2; exit 1;;
 	esac
     done
-    if [[ ${VARNAME-} == ? ]] ; then
-	echo "error, exiting..." >&2
-	return 1
-    fi
+    shift $(($OPTIND - 1))
     if [[ $CLEAN ]] ; then
 	_clean
 	return 1
